// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwvOBH_9K_gcsBMTETc9YEGQQ2tQVFek',
    appId: '1:401440372070:web:a7a67c72b6b10d7b11c4a7',
    messagingSenderId: '401440372070',
    projectId: 'tashveer-39ecc',
    authDomain: 'tashveer-39ecc.firebaseapp.com',
    storageBucket: 'tashveer-39ecc.appspot.com',
    measurementId: 'G-WKC197ESGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIu4twFLKbz85nChBKyXkPFarTwMCv6Lc',
    appId: '1:401440372070:android:05ae4618cb8bd28c11c4a7',
    messagingSenderId: '401440372070',
    projectId: 'tashveer-39ecc',
    storageBucket: 'tashveer-39ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJIPGBTGBEm6_eb5rj76w_tQhXFFKfMtI',
    appId: '1:401440372070:ios:68f63b94e2bd870a11c4a7',
    messagingSenderId: '401440372070',
    projectId: 'tashveer-39ecc',
    storageBucket: 'tashveer-39ecc.appspot.com',
    iosClientId: '401440372070-scns7cskk3b2aca6oa9md1ada0r6mcq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tashveer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJIPGBTGBEm6_eb5rj76w_tQhXFFKfMtI',
    appId: '1:401440372070:ios:68f63b94e2bd870a11c4a7',
    messagingSenderId: '401440372070',
    projectId: 'tashveer-39ecc',
    storageBucket: 'tashveer-39ecc.appspot.com',
    iosClientId: '401440372070-scns7cskk3b2aca6oa9md1ada0r6mcq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tashveer',
  );
}
